### ISSUE TITLE
Can not include lib in my project

### ISSUE THREAD

**Issue by hackash** [mikefowler/instajam#11]
When I try to init Api it trows TypeError: Instajam.init is not a function. Instajam reference is empty object. What is the reason?

**Comment by mikefowler** [comment]
Hmm, looks like there was an issue with build products in `v2.0.2`. Just pushed a fix, could you try now @hackash? Version should now be `v2.0.3`.

**Comment by hackash** [comment]
Thank you for your answer. I'll try it as soon as posible.

**Comment by arqex** [comment]
Hi, last version in NPM is 2.0.2. Could you update it?

Thanks for your awesome work.

**Comment by mikefowler** [comment]
Bumped. Thanks for the reminder, @arqex!
