### ISSUE TITLE
localStorage.setItem cannot be used in Safari private browsing

### ISSUE THREAD

**Issue by stuartkeith** [mikefowler/instajam#14]
Just thought I'd let you know that instajam will not work in private browsing mode in Safari (and possibly other browsers).

localsStorage.setItem throws an exception, and will not store anything. This means that `options.data.access_token = localStorage.getItem('instagram_access_token')` will always return null.

**Comment by rinatkhaziev** [comment]
That's Safari thing, it doesn't allow either localStorage or sessionStorage in private mode.
