### ISSUE TITLE
NPM support

### ISSUE THREAD

**Issue by truckingsim** [mikefowler/instajam#9]
We use browserify for our project and would be nice if we could load this in through npm.

**Comment by mikefowler** [comment]
That would be nice. I can probably throw that together in the next week or so, @truckingsim. (Or feel free to push up a pull request!)

**Comment by truckingsim** [comment]
This is more on your end since you're the owner you have to do the publish.  You also will have to update the package.json with the `main` key.  Which points to the full version (not min), of the compiled JS.  Once you do that npm should let you publish.

Also as a side note, I recommend adding `grunt-update-json` to your build process.  This will let you keep one file (say package.json) up to date with common information (description, name, version) and will sync it with other files (say bower.json).  I added this as part of my build process when I do a release.  I mention this because right now your bower.json and package.json versions are out of sync.

**Comment by mikefowler** [comment]
@truckingsim: you should be all set to use Instajam with Browserify now :+1:

**Comment by truckingsim** [comment]
Thanks, will give it a shot tomorrow!
